In [10]:
import csv
import sys,os
import datetime
import pandas as pd
import numpy as np

In [11]:
os.path.join('AppCantine','cantinedata','predict', 'xgb_model_grcv.json')

'AppCantine\\cantinedata\\predict\\xgb_model_grcv.json'

In [12]:
your_djangoproject_home="D:/Eric/Simplon/GaspillageCantine/Repos/Simplon_E1_EricBertrand_GaspillageCantine_App/AppCantine"

sys.path.append(your_djangoproject_home)
os.environ['DJANGO_SETTINGS_MODULE'] ='AppCantine.settings'
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'rest.settings')
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

import django


django.setup()
from cantinedata.models import Fréquentation

In [13]:
from django.db import connection
from asgiref.sync import sync_to_async
from django.db.models import Sum

In [2]:
import pickle
import xgboost as xgb

In [7]:
path_model

'..\\predict\\xgb_model_grcv.json'

In [10]:
os.listdir("../predict/")

['artefacts_model_xgb_grcv.pkl', 'xgb_model_grcv.json']

In [3]:
# create path to models
path_model = os.path.join('../predict', 'xgb_model_grcv.json')
path_artefacts = os.path.join('../predict', 'artefacts_model_xgb_grcv.pkl')
predict_model = xgb.XGBRegressor()
predict_model.load_model(path_model)


In [4]:
# these will be accessible via this class
with open(path_artefacts, 'rb') as f:
   dump_var = pd.read_pickle(f)


In [5]:
global XParam 
XParam = dump_var['X']
global datetable 
datetable = dump_var['Date']

global getDateIndex
getDateIndex = lambda str1 : datetable[datetable == str1].index.min()
getDateParam = lambda str1 : XParam[getDateIndex(str1)]

In [6]:
date1 = '2011-01-03'


In [7]:
getDateParam(date1)

array([1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 2.0110e+03, 1.1883e+04, 1.0000e+00, 1.0000e+00,
       4.0000e+00])

In [9]:
# build response
response = predict_model.predict([getDateParam(date1)])
response

array([12608.066], dtype=float32)

In [37]:
X = dump_var['X']
datetable = dump_var['Date']

In [50]:
getDateIndex = lambda str1 : datetable[datetable == str1].index.min()

In [59]:
getDateIndex('toto')

nan

In [53]:
getDateParam = lambda str1 : X[getDateIndex(str1)]

In [51]:
getDateIndex('2011-01-03')

0

In [54]:
getDateParam('2011-01-03')

array([1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 2.0110e+03, 1.1883e+04, 1.0000e+00, 1.0000e+00,
       4.0000e+00])

In [52]:
getDateIndex(datetable[11])

11

In [56]:
getDateParam(datetable[11])

array([1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       1.0000e+00, 2.0110e+03, 1.1883e+04, 4.0000e+00, 5.0000e+00,
       4.0000e+00])

In [57]:
getDateParam('toto')

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [44]:
row_num.min()

0

In [20]:
datetable1 = datetable.apply( lambda tt1 : datetime.datetime.fromtimestamp(tt1) ) 

TypeError: 'Timestamp' object cannot be interpreted as an integer

In [13]:
X.shape

(1431, 21)

In [15]:
datetable[0]

Timestamp('2011-01-03 00:00:00')